use_frameworks!

target 'UCPortal_Example' do
  pod 'UCPortal', :path => '../'

  target 'UCPortal_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Kanna', '~> 2.0.0'
    
  pod 'Nimble', '~> 5.1.1'
  end
end
